name: 'Spectral comment'
description: 'Comments pull requests with Spectral linter outputs'
inputs:
  github-token:
    required: true
    description: 'Github token'
  file-glob:
    required: true
    description: The file path to lint with Spectral
    default: '*.oas.{json,yml,yaml}'
  spectral-root-ruleset:
    required: true
    description: Ruleset file to load in Spectral
    default: 'spectral:oas'
  spectral-path-ruleset:
    required: true
    description: Ruleset file to load in Spectral
    default: 'spectral:oas'
  spectral-schema-ruleset:
    required: true
    description: Ruleset file to load in Spectral
    default: 'spectral:oas'
  github-url:
    description: 'Github URL'
    default: 'https://github.com'
runs:
  using: 'node12'
  main: 'src/index.js'
branding:
  icon: check-square
  color: purple
