name: Action Preview

concurrency:
  group: "preview-${{ github.ref }}"
  cancel-in-progress: false

on:
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm build

      - name: Run Tests
        run: pnpm test

      - name: Checkout API Specs
        uses: actions/checkout@v4
        with:
          repository: sailpoint-oss/api-specs
          path: api-specs
          ref: main
      
      - name: Speccy Resolve
        run: |
          npm install -g speccy@0.8.7
              speccy resolve --quiet api-specs/idn/sailpoint-api.v2024.yaml -o packages/gateway-rulesets/src/v2024.yaml
              echo "✅ Output path for v2024.yaml: $(pwd)/packages/gateway-rulesets/src/v2024.yaml"
              ls -l packages/gateway-rulesets/src/v2024.yaml || echo "❌ v2024.yaml not found"
              speccy resolve --quiet api-specs/idn/sailpoint-api.v2025.yaml -o packages/gateway-rulesets/src/v2025.yaml

      - name: generate API State Map
        working-directory: packages/gateway-rulesets/src
        run: node ../../../generateApiStateMap.js

      - name: Preview Action
        uses: ./packages/github-spectral-comment
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file-glob: packages/test-files/sailpoint-api.OpenAPI.yaml,packages/test-files/v2024/paths/account.yaml,packages/test-files/sp-gateway-routes.yaml
          spectral-root-ruleset: ../../../sailpoint-rulesets/root-ruleset.yaml
          spectral-path-ruleset: ../../../sailpoint-rulesets/path-ruleset.yaml
          spectral-schema-ruleset: ../../../sailpoint-rulesets/schema-ruleset.yaml
          spectral-gateway-ruleset: ../../../gateway-rulesets/gateway-ruleset.yaml