name: Action Preview

on:
  pull_request:
    branches:
        - main

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm build

      - name: Run Tests
        run: pnpm test

      - name: Preview Action
        uses: ./packages/github-spectral-comment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file-glob: packages/test-files/OpenAPI.yaml
          spectral-root-ruleset: packages/sailpoint-rulesets/root-ruleset.yaml
          spectral-path-ruleset: packages/sailpoint-rulesets/path-ruleset.yaml
          spectral-schema-ruleset: packages/sailpoint-rulesets/schema-ruleset.yaml
